[package]
name = "viewer"
version = "0.1.0"
edition = "2021"

[dependencies]
vcd = "0.7"

[dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic"
default-features = false
features = ["winit", "wgpu"]